from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol

from PySide6.QtWidgets import QComboBox, QLabel, QSpinBox, QVBoxLayout, QWidget

from fractal_studio.backend import CoreBackend
from fractal_studio.editor import ColorCubeEditor, PalettePreviewWidget
from fractal_studio.state import FavoriteSnapshot
from fractal_studio.viewport import FractalParamsPanel, FractalViewportWidget


class ViewportPanelPorts(Protocol):
    @property
    def backend(self) -> CoreBackend: ...

    def show_status(self, message: str) -> None: ...
    def set_aspect_ratio_combo(self, combo: QComboBox) -> None: ...
    def on_aspect_ratio_changed(self, index: int) -> None: ...
    def set_viewport(self, viewport: FractalViewportWidget) -> None: ...
    def set_viewport_hint_label(self, label: QLabel) -> None: ...


class PalettePanelPorts(Protocol):
    def set_preview_widgets(
        self,
        preview_palette: PalettePreviewWidget,
        preview_legacy: PalettePreviewWidget,
    ) -> None: ...
    def set_palette_summary_labels(
        self, point_summary: QLabel, palette_summary: QLabel
    ) -> None: ...


class ColormapPanelPorts(Protocol):
    @property
    def backend(self) -> CoreBackend: ...

    def show_status(self, message: str) -> None: ...
    @property
    def backend_profile(self): ...

    @property
    def viewport(self) -> FractalViewportWidget | None: ...

    def set_editor(self, editor: ColorCubeEditor) -> None: ...
    def update_palette_previews(self, palette) -> None: ...
    def update_control_summary(self, points) -> None: ...
    def save_palette_json(self) -> None: ...
    def load_palette_json(self) -> None: ...
    def export_legacy_map(self) -> None: ...


class BackendPanelPorts(Protocol):
    def set_backend_state_label(self, label: QLabel) -> None: ...


class ExportPanelPorts(Protocol):
    def refresh_export_presets(self, combo: QComboBox) -> None: ...
    def on_export_clicked(self) -> None: ...
    def custom_size_values(self) -> tuple[int, int]: ...
    def set_custom_size_boxes(
        self, width_box: QSpinBox, height_box: QSpinBox
    ) -> None: ...
    def on_export_preset_changed(self, index: int) -> None: ...
    def apply_aspect_ratio_mode(self, update_combo: bool) -> None: ...


class FavoritesPanelPorts(Protocol):
    def set_favorites_scroll_container(
        self, widget: QWidget, layout: QVBoxLayout
    ) -> None: ...
    def load_favorites(self) -> list[FavoriteSnapshot]: ...
    def add_favorite_row(self, favorite: FavoriteSnapshot) -> None: ...
    def save_favorite(self) -> None: ...
    def delete_selected_favorite(self) -> None: ...


class SidebarPanelPorts(Protocol):
    @property
    def backend_profile(self): ...

    def set_params_panel(self, panel: FractalParamsPanel) -> None: ...
    def connect_params_and_viewport(self) -> None: ...
    def backend_state_message(self) -> str: ...


@dataclass(frozen=True)
class MainWindowSectionsPorts:
    viewport: ViewportPanelPorts
    palette: PalettePanelPorts
    colormap: ColormapPanelPorts
    backend: BackendPanelPorts
    export: ExportPanelPorts
    favorites: FavoritesPanelPorts
    sidebar: SidebarPanelPorts
